### ISSUE TITLE
SDK v1.6.4 installation fail

### ISSUE THREAD

**Issue by ozorOzora** [iExecBlockchainComputing/iexec-sdk#31]
Cher iExec,

i've been trying to install the latest version of your SDK (1.6.4) through npm's `npm -g install iexec` but it seems to always fail. I tried the installer on different systems: Windows 8, Mac, and [even on the KataKoda's server instance](https://www.katacoda.com/sulliwane/scenarios/ffmpeg).

Here is the error log:
```
6156 verbose stack Error: sha3@1.2.0 install: `node-gyp rebuild`
6156 verbose stack Exit status 1
6156 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
6156 verbose stack     at emitTwo (events.js:126:13)
6156 verbose stack     at EventEmitter.emit (events.js:214:7)
6156 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
6156 verbose stack     at emitTwo (events.js:126:13)
6156 verbose stack     at ChildProcess.emit (events.js:214:7)
6156 verbose stack     at maybeClose (internal/child_process.js:925:16)
6156 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
6157 verbose pkgid sha3@1.2.0
6158 verbose cwd D:\Elias_OUSGHIR\Images\Création\prog\iexec-test
6159 verbose Windows_NT 6.3.9600
6160 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "iexec"
6161 verbose node v8.9.4
6162 verbose npm  v5.6.0
6163 error code ELIFECYCLE
6164 error errno 1
6165 error sha3@1.2.0 install: `node-gyp rebuild`
6165 error Exit status 1
6166 error Failed at the sha3@1.2.0 install script.
```

Do you have any idea what's going on? I'm looking forward to test your SDK.
Merci d'avance!

**Edit:** Version 1.6.3 installed successfully

**Comment by sulliwane** [comment]
Thank you @ozorOzora for your report.

Version [v1.6.6](https://github.com/iExecBlockchainComputing/iexec-sdk/releases/tag/v1.6.6) fixes this issue, feel free to reopen if you still experience a problem.
